/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("grdl.demo.kotlin-application-conventions")
    id("org.jetbrains.kotlin.jvm") version "1.8.10"
    application
}

repositories {
    mavenCentral();
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.1")
    implementation("com.google.guava:guava:31.1-jre")
}

application {
    // Define the main class for the application.
    mainClass.set("grdl.demo.app.AppKt")
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}
