/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package grdl.demo.app

import grdl.demo.utilities.StringUtils

import org.apache.commons.text.WordUtils

class App {
    //val tokens = StringUtils.split(MessageUtils.getMessage())
    //val result = StringUtils.join(tokens)
    //println(WordUtils.capitalize(result))

    val greeting:String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
}
